### PR TITLE
Enable `frozen_string_literal: true` in `logger.rb`.

### PR DESCRIPTION
**Pull request by ioquatix**
Is there any reason not to do this?

### CODE REVIEW

**Comment by ioquatix** [comment]
@sonots what do you think of this?

**Comment by sonots** [comment]
I remember the `frozen_string_literal: false` line was introduced to all (most of) standard libraries when it was introduced into ruby.

Also, before I merged `.freeze` patch. You should be able to remove them.

Logically thinking, `frozen_string_literal` should be able to be `true` as long as we do not have a string mutated like `a = ''; a << 'foo'` (it is one example, though). 
We need to examine (It looks it is okay changing to `true` with my hurried look).

**Comment by ioquatix** [comment]
I cannot find any example of mutable string and all tests pass so I think this is okay.

**Comment by ioquatix** [comment]
Because `frozen_string_literal: true` is only advisory, I don't believe we should remove `.freeze`. But please advise me on what you want and I can do it.

**Comment by sonots** [comment]
I want to remove unnecessary .freeze if we make `frozen_string_literal: true`

**Comment by sonots** [comment]
I will take care of others, let me merge once.

**Comment by sonots** [comment]
Let me see. 
https://bugs.ruby-lang.org/issues/11473#note-53

matz says

>  So I officially abandon making frozen-string-literals default (for Ruby3).

It does not mean `frozen_string_literal: true` will be dropped, but should we still use `frozen_string_literal: true`?

Remember that `frozen_string_literal: true` was prepared as a migration path for making frozen-string-literals default (for Ruby3).

**Comment by ioquatix** [comment]
Sorry I was sleeping but everything you did looks good!

**Pull request merged**
