### PR TITLE
Custom test library replace to test-unit gem

### PR DESCRIPTION
**Pull request by komagata**
Remove custom test library.
I transport only custom assertions into assertions.rb.

Reference: #27

custom assertions:

- assert_in_out_err
- assert_separately
- assert_file

### CODE REVIEW

**Comment by sonots** [comment]
Thanks! I will check later!

**Comment by hsbt** [comment]
I prefer this patch. I will consider backporting this change to the ruby core repository after merging.

**Comment by hsbt** [comment]
@sonotsI I merged this because I start to work to migrate this change on the ruby core repository. If you have any concerns, Please ping me on the bugs.ruby-lang.org or this repostiory.

**Comment by sonots** [comment]
ok

**Pull request merged**
