### PR TITLE
Add ruby 2.3.8, ruby 2.4.5, 2.6.0 and update 2.5 in travis

### PR DESCRIPTION
**Pull request by colby-swandale**
I figured that it would be good practice to test all the supported versions of ruby in travis.

### CODE REVIEW

**Comment by yuki24** [comment]
The failure looks legit, though I think we should just go ahead and merge it.

@hsbt what do you think?

**Comment by colby-swandale** [comment]
i will try to solve the issues with 2.3.8 before this PR is merged.

**Comment by colby-swandale** [comment]
Maybe we should just skip the breaking tests on 2.3.8? @hsbt What's the policy on what versions of Ruby gemified gems support?

**Comment by ioquatix** [comment]
I have had issues running specs on MacOS too.

**Comment by ioquatix** [comment]
I have made local branch `update-travis` and merged changes into it. I will try to get this working as expected.

**Comment by ioquatix** [comment]
@colby-swandale thanks for your contributions.

**Comment by ioquatix** [comment]
Okay I've made 2.3 allowed failure and merged to master, at least we have some visibility on what's going wrong and at some point someone can test. I am also going to add testing on MacOS.

**Pull request closed without merging**
