### PR TITLE
split logger classes/modules into separate files

### PR DESCRIPTION
**Pull request by colby-swandale**
The entire Logger library is currently sitting in a single file. This makes the library not easy read and work on.

This PR splits up the code base and puts each class/module inside `Logger` into it's own file. This should help make the code easier to read.

Note: I think i've set the `require` correctly for ruby-src but verification would be helpful before this is considered for merging.

### CODE REVIEW

**Comment by ioquatix** [comment]
@sonots if I tidy this up can I merge into master?

**Comment by sonots** [comment]
I was thinking to do this by myself.

**Comment by ioquatix** [comment]
If you want to do it please do, otherwise I'm happy to help.

**Comment by ioquatix** [comment]
I wonder if we can convert test to Rspec... it's so much easier to use.

**Comment by sonots** [comment]
test-unit with power-assert is much easier to use for me.

**Comment by ioquatix** [comment]
How do you run individual tests?

**Comment by ioquatix** [comment]
Maybe we can add documentation about how to run individual tests and a few other examples to README.

**Comment by colby-swandale** [comment]
@ioquatix can can specify an individual test via `rake test TEST=path/to/test`.

Documentation would be great 👍

**Comment by sonots** [comment]
I'll work to rebase and merge master based on this. Let me close once.

**Comment by sonots** [comment]
Merged. Thanks!

**Pull request closed without merging**
